abouttrip/abouttrip/urls.py
from django.contrib import admin
from django.urls import path, include, register_converter, re_path
from django.conf.urls.static import static
from trips import views
from abouttrip import converters, settings

register_converter(converters.FourDigitYearConverter, "year4")
handler404 = views.page_not_found

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Путешествия по миру"

urlpatterns = [
    path('', views.TripsHome.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('about/', views.about, name='about'),
    path('addpage/', views.AddPage.as_view(), name='add_page'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.login, name='login'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
    # path('category/<int:cat_id>/', views.show_category, name='category'),
    path('category/<slug:cat_slug>/', views.TripsCategory.as_view(), name='category'),
    path('tag/<slug:tag_slug>/', views.TagPostList.as_view(), name='tag'),
    path('edit/<slug:slug>/', views.UpdatePage.as_view(), name='edit_page'),
    path('delete/<slug:slug>/', views.DeletePage.as_view(), name='delete_page'),
    path("__debug__/", include("debug_toolbar.urls")),
    path('users/', include("users.urls", namespace="users")),

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

abouttrip/trips/urls.py
from django.urls import path
from . import views

urlpatterns = [
]

abouttrip/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, \
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/',
         PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name='password_change_done'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-reset/',
         PasswordResetView.as_view(template_name="users/password_reset_form.html",
                                   email_template_name="users/password_reset_email.html",
                                   success_url=reverse_lazy("users:password_reset_done")),
         name='password_reset'),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",
                                          success_url=reverse_lazy(
                                              "users:password_reset_complete")),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),

]
app_name = "users"

abouttrip/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
import datetime


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        User = get_user_model()
        model = User
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля',
                                widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        User = get_user_model()
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name',
                  'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name':
                forms.TextInput(attrs={'class': 'form-input'}),
            'last_name':
                forms.TextInput(attrs={'class': 'form-input'}),
        }


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='E-mail',
                            widget=forms.TextInput(attrs={'class': 'form-input'}))
    this_year = datetime.date.today().year
    date_birth = forms.DateField(
        widget=forms.SelectDateWidget(years=tuple(range(this_year - 70, this_year - 5))))

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'email', 'date_birth', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name':
                forms.TextInput(attrs={'class': 'form-input'}),
            'last_name':
                forms.TextInput(attrs={'class': 'form-input'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль",
                                   widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль",
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля",
                                    widget=forms.PasswordInput(attrs={'class': 'forminput'}))

abouttrip/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
<h1>Авторизация</h1>
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}"/>
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label}}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>

    <p>
        <button type="submit">Войти</button>
    </p>

</form>
{% endblock %}

abouttrip/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block content %}
<h1>Пароль успешно изменен!</h1>
<p>Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

abouttrip/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block content %}
<h1>Изменение пароля</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}
    </div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p>
        <button type="submit">Изменить пароль</button>
    </p>
</form>
{% endblock %}

abouttrip/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block content %}
<h1>Пароль изменен</h1>
<p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для<a
        href="{% url 'users:login' %}">входа в систему</a>.</p>
{% endblock %}

abouttrip/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}

<h1>Новый пароль</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}
    </div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p>
        <button type="submit">Сохранить</button>
    </p>
</form>
{% endblock %}

abouttrip/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% load i18n %}
{% block content %}
<h1>Сброс пароля</h1>
<p>Мы отправили вам по электронной почте инструкции по установке пароля, если учетная запись существует, на указанный вами адрес электронной почты. Вы должны получить их в ближайшее время.</p>
<p>Если вы не получаете электронное письмо, пожалуйста, убедитесь, что вы указали адрес, на который указывали при регистрации, и проверьте папку со спамом</p>
{% endblock %}

abouttrip/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

abouttrip/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block content %}
<h1>Восстановление пароля</h1>
<form method="post">
    {% csrf_token %}
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p>
        <button type="submit">Сбросить по Email</button>
    </p>
</form>
{% endblock %}

abouttrip/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<h1>Профиль</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% if user.photo %}
        <p ><img src="{{ user.photo.url }}">
    {% else %}
        <p ><img src="{{ default_image }}">
    {% endif %}
    <div class="form-error">{{ form.non_field_errors }}
    </div>

    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <hr>
    <p><a href="{% url 'users:password_change' %}">Сменить пароль</a></p>
    <p>
        <button type="submit">Сохранить</button>
    </p>
</form>
{% endblock %}

abouttrip/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<h1>Регистрация</h1>
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p ><button type="submit">Регистрация</button></p>
</form>

{% endblock %}

abouttrip/templates/users/register_done.html
{% extends 'base.html' %}

{% block content %}
<h1>Добро пожаловать!</h1>
<p>Вы успешно зарегистрировались на сайте! Для входа в систему необходимо авторизоваться по этой
    <a href="{% url 'users:login' %}">ссылке</a>
</p>

{% endblock %}